### ISSUE TITLE
Solved but not in the correct orientation, still need to be solved?

### ISSUE THREAD

**Issue by sam0737** [dwalton76/rubiks-cube-NxNxN-solver#3]
I have a 4x4x4 cube in this state:
`FFFFFFFFFFFFFFFFLLLLLLLLLLLLLLLLUUUUUUUUUUUUUUUUBBBBBBBBBBBBBBBBRRRRRRRRRRRRRRRRDDDDDDDDDDDDDDDD`
It's solved, but maybe not oriented correctly.

The solutions that were given is:
```
Solution: L R F2 L R' D2 F2 L2 U2 R2 B2 R2 U2
13 steps to solve 3x3x3
13 steps total
```
I am expecting no steps at all - it's simply solved.

**Comment by dwalton76** [comment]
Good catch, fixed now
