### ISSUE TITLE
ImportError: No module named 'pyhashxx'

### ISSUE THREAD

**Issue by Steven438** [dwalton76/rubiks-cube-NxNxN-solver#52]
I just installed this solver on my Raspberry pi 3 model B+ and when attempting to solve a 3x3x3 or 2x2x2 give me this error: ImportError: No module named 'pyhashxx'.
I tried this solver a month ago on Raspberry pi 2 and worked very well. I don't know what happened. Please help me, if you need a screenshot of the error here is it:
![2018-06-27-091613_1824x984_scrot](https://user-images.githubusercontent.com/40627632/41964934-d371b4d0-79ea-11e8-87a9-3b699aad18bb.png)#

The state of the 3x3x3 cube is from yours example. Thank you and hope you will reply to this! 
Steven

**Comment by dwalton76** [comment]
Sorry, I need to update the install instructions in the README.  Try `sudo pip3 install pyhashxx`

**Comment by Steven438** [comment]
ok i tried and now works. Thanks and sorry for starting this issue.

**Comment by dwalton76** [comment]
@steven438 no worries at all please open issues if you hit bugs. I’ve updated the README to include this step.
