### ISSUE TITLE
Execution time?

### ISSUE THREAD

**Issue by nathannunes** [dwalton76/rubiks-cube-NxNxN-solver#60]
How do I get the execution time of kociemba? also I keep getting an error, something like "sum  is 9" how do I fix this?

**Comment by dwalton76** [comment]
@nathannunes sorry just saw this :( You can run kociemba on its own to time it, the state string of the cube that is passed to kociemba should be in the log output of the solver.

For the "sum is 9" error can you send me the cube you are trying to solve?
