### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by BodyCSoulN** [dwalton76/rubiks-cube-NxNxN-solver#68]
when i execute "./rubiks-cube-solver.py --state LLFBRBFUDULBULBBDDUBBBBLDFDULDLURFBDFRLDUFDBRLDUFBLURFRFRDRBULFBLLLBURUFRFURDDLBULLLRLRDFRDRBBRUDFDUFRBUDULFDUFULDFRBRBULLUFFBLRDDDDFRRBUBRLBUUFFRRDFF"
the error is "No such file or directory: 'lookup-tables/lookup-table-5x5x5-step11-LR-centers-stage-t-center-only.state_index.gz'"
so, what should i do?

**Comment by BodyCSoulN** [comment]
i solved it when i create a directory named "lookup-tables"

**Comment by abunickabhi** [comment]
Maybe in the github description, one more line can be added, where we have mkdir lookup-tables written, so the setup process is more seamless.

**Comment by dwalton76** [comment]
@BodyCSoulN @abunickabhi sorry for taking months to respond.  Thank you for reporting the issue. It has been fixed in master.
