### ISSUE TITLE
Non-issue: author of the 2x2x2 codegolf solution

### ISSUE THREAD

**Issue by jakobkogler** [dwalton76/rubiks-cube-NxNxN-solver#69]
Hey. I'm the original creator of the 2x2x2 solver that you took as template for your solver https://github.com/dwalton76/rubiks-cube-NxNxN-solver/blob/master/rubikscubennnsolver/RubiksCube222.py. Don't worry, I don't care about copyright or so, you can do with the code whatever you want.

I just randomly found this repository, and found it very funny that you used my solution for your legitimate project. As my code was never intended to be used as such. I did not design my solver to be especially good, fast, easy to understand or usable. The solution was born under the constraint of getting it as small as possible, and at the same time getting it to run in under 1 second. 
Because of the size constrains, I couldn't effort any code that reorganizes the cube into a nice format, or use any big lookup tables. After trying with a few different approaches, I settled down with this bidirectional BFS approach. I would have liked to simply do a BFS, like the solution in C did, but my inefficient data structures and way of applying moves was too slow for that, and speeding these steps up would have taken much more characters than switching to bidirectional BFS. It's a pretty stupid implementation. It just uses Python's dictionaries to store states, instead of only visiting new nodes I visit them multiple times (E.g. I actually perform the move sequence `R R' R R' R R'`, as checking for such stupid sequences is expensive in code size), and I did every single ugly trick that I knew.

I'm sure it's possible to generate a solver in Python that is much, much cleaner, and 100x faster than my ugly solution. Even storing a full lookup table with the optimal solutions for every possible scramble is quite easy, as there are so few possibilities on a 2x2x2.

Btw, If you have any more questions about my code, don't hesitate to ping me.

**Comment by dwalton76** [comment]
Hi @jakobkogler , that is very cool, thanks for reaching out :)  And also thank you for writing that code golf 2x2x2 solver years ago.  At the time I was googling around for solvers for various sized cubes...3x3x3 was easy and I found your 2x2x2 solver pretty quickly.  I managed to find a 4x4x4 solver but hit a wall for 5x5x5 and larger which led me to start this project. 

At some point I did create a lookup-table based 2x2x2 solver but that was just one more lookup table for the user to download and your solver worked well enough so I stuck with it.  I did ungolf it a good bit so I could figure out how it worked but other than that I didn't change it.
