### ISSUE TITLE
made kociemba barf

### ISSUE THREAD

**Issue by ChaseOSDeveloper** [dwalton76/rubiks-cube-NxNxN-solver#92]
i did some tests this morning but now it doesn't work.
![image](https://user-images.githubusercontent.com/90874854/146654849-b76c66a5-2ebc-4cfe-a2e5-b5c1bc0c36b0.png)

**Comment by dwalton76** [comment]
Can you post the cube string that you gave to the solver

**Comment by ChaseOSDeveloper** [comment]
RRBBUFBFBRLRRRFRDDURUBFBBRFLUDUDFLLFFLLLLDFBDDDUUBDLUU
the testing one

**Comment by dwalton76** [comment]
What does `which kociemba` show?  If it returns blank, you need to do these steps from the install instructions in the README
```
$ git clone https://github.com/dwalton76/kociemba.git
$ cd ~/kociemba/kociemba/ckociemba/
$ make
$ sudo make install
```

**Comment by ChaseOSDeveloper** [comment]
its regular

**Comment by ChaseOSDeveloper** [comment]
but

**Comment by ChaseOSDeveloper** [comment]
ur solver doesnt work but i might have not set up something correctly but I don't know

**Comment by ChaseOSDeveloper** [comment]
i forgot to install kociemba
